<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class VehicleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            [
                'vehicle_name' => 'Toyota Corolla',
                'type' => 'Sedan',
                'model' => '2020',
                'engine_type' => 'Gasoline',
                'engine_number' => '123ABC456',
                'license_plate' => 'B1234XYZ',
                'registration_expiry_date' => '2025-12-01',
                'year_of_first_immatriculation' => 2020,
                'fuel_type' => 'Petrol',
                'kilometer' => 15000,
                'daily_rate' => 300000.00,
                'gearbox' => 'Automatic',
                'number_of_seats' => 4,
                'options' => 'Air Conditioning, GPS',
                'document' => 'car-doc-1.pdf',
                'notes' => 'In good condition.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'vehicle_name' => 'Honda Civic',
                'type' => 'Sedan',
                'model' => '2019',
                'engine_type' => 'Gasoline',
                'engine_number' => '456DEF789',
                'license_plate' => 'B5678ABC',
                'registration_expiry_date' => '2024-11-01',
                'year_of_first_immatriculation' => 2019,
                'fuel_type' => 'Petrol',
                'kilometer' => 20000,
                'daily_rate' => 350000.00,
                'gearbox' => 'Automatic',
                'number_of_seats' => 5,
                'options' => 'Bluetooth, Sunroof',
                'document' => 'car-doc-2.pdf',
                'notes' => 'Well-maintained.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'vehicle_name' => 'Suzuki Ertiga',
                'type' => 'MPV',
                'model' => '2021',
                'engine_type' => 'Gasoline',
                'engine_number' => '789GHI012',
                'license_plate' => 'B9876DEF',
                'registration_expiry_date' => '2026-05-10',
                'year_of_first_immatriculation' => 2021,
                'fuel_type' => 'Petrol',
                'kilometer' => 5000,
                'daily_rate' => 400000.00,
                'gearbox' => 'Manual',
                'number_of_seats' => 7,
                'options' => 'Air Conditioning, Power Windows',
                'document' => 'car-doc-3.pdf',
                'notes' => 'Newly purchased, low mileage.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'vehicle_name' => 'Nissan X-Trail',
                'type' => 'SUV',
                'model' => '2020',
                'engine_type' => 'Diesel',
                'engine_number' => '012JKL345',
                'license_plate' => 'B5432JKL',
                'registration_expiry_date' => '2024-08-15',
                'year_of_first_immatriculation' => 2020,
                'fuel_type' => 'Diesel',
                'kilometer' => 25000,
                'daily_rate' => 500000.00,
                'gearbox' => 'Automatic',
                'number_of_seats' => 8,
                'options' => 'Leather Seats, GPS, Sunroof',
                'document' => 'car-doc-4.pdf',
                'notes' => 'Well-maintained, used for long trips.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'vehicle_name' => 'Isuzu D-Max',
                'type' => 'Pickup',
                'model' => '2022',
                'engine_type' => 'Diesel',
                'engine_number' => '345JKL678',
                'license_plate' => 'B1234ABC',
                'registration_expiry_date' => '2027-06-20',
                'year_of_first_immatriculation' => 2022,
                'fuel_type' => 'Diesel',
                'kilometer' => 3000,
                'daily_rate' => 600000.00,
                'gearbox' => 'Manual',
                'number_of_seats' => 4,
                'options' => 'Off-road Package, Bluetooth',
                'document' => 'car-doc-5.pdf',
                'notes' => 'Perfect for off-road use.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'vehicle_name' => 'Toyota Hiace',
                'type' => 'Van',
                'model' => '2018',
                'engine_type' => 'Diesel',
                'engine_number' => '456DEF890',
                'license_plate' => 'B6543XYZ',
                'registration_expiry_date' => '2025-10-12',
                'year_of_first_immatriculation' => 2018,
                'fuel_type' => 'Diesel',
                'kilometer' => 50000,
                'daily_rate' => 700000.00,
                'gearbox' => 'Automatic',
                'number_of_seats' => 12,
                'options' => 'AC, Leather Seats',
                'document' => 'car-doc-6.pdf',
                'notes' => 'Ideal for group transport.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'vehicle_name' => 'Mercedes-Benz Sprinter',
                'type' => 'Van',
                'model' => '2020',
                'engine_type' => 'Diesel',
                'engine_number' => '678XYZ345',
                'license_plate' => 'B9876DEF',
                'registration_expiry_date' => '2026-12-10',
                'year_of_first_immatriculation' => 2020,
                'fuel_type' => 'Diesel',
                'kilometer' => 60000,
                'daily_rate' => 800000.00,
                'gearbox' => 'Manual',
                'number_of_seats' => 15,
                'options' => 'Air Conditioning, GPS, Large Cargo Space',
                'document' => 'car-doc-7.pdf',
                'notes' => 'Used for cargo and group transport.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'vehicle_name' => 'Ford Ranger',
                'type' => 'Pickup',
                'model' => '2021',
                'engine_type' => 'Diesel',
                'engine_number' => '234JKL567',
                'license_plate' => 'B4321LMN',
                'registration_expiry_date' => '2026-02-25',
                'year_of_first_immatriculation' => 2021,
                'fuel_type' => 'Diesel',
                'kilometer' => 15000,
                'daily_rate' => 650000.00,
                'gearbox' => 'Automatic',
                'number_of_seats' => 5,
                'options' => '4WD, Bluetooth, Navigation',
                'document' => 'car-doc-8.pdf',
                'notes' => 'Great for both city and off-road use.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'vehicle_name' => 'Chevrolet Tahoe',
                'type' => 'SUV',
                'model' => '2023',
                'engine_type' => 'Gasoline',
                'engine_number' => '345XYZ678',
                'license_plate' => 'B8765DEF',
                'registration_expiry_date' => '2027-07-01',
                'year_of_first_immatriculation' => 2023,
                'fuel_type' => 'Petrol',
                'kilometer' => 2000,
                'daily_rate' => 900000.00,
                'gearbox' => 'Automatic',
                'number_of_seats' => 7,
                'options' => 'Leather Seats, Air Conditioning, Sunroof',
                'document' => 'car-doc-9.pdf',
                'notes' => 'New car with low mileage.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ];

        DB::table('vehicles')->insert($data);
    }
}
